name: basic

on: 
  push:
    branches:
      - main

  # pull_request:
  #   branches:
  #     - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
     
      - name: list
        run: ls -al

      - name: build
        run: |
          docker build -t nikhil2254/myapp:latest .

      - name: push
        env:
          usr: ${{secrets.usr}}
          psd: ${{secrets.psd}}
        run: |

          docker login -u "$usr" -p "$psd"
          
        
          docker image push nikhil2254/myapp:latest
