name: basic

on: 
  push:
    branches:
      - main

  # pull_request:
  #   branches:
  #     - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
     
      - name: list
        run: ls -al

      - name: build
        run: |
          docker build -t myapp:latest .
          docker run -d -p 8080:80 myapp:latest
